version: '3'
services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    environment:
      - NEXTCLOUD_ADMIN_USER=admin #admin password for your nextcloud account
      - NEXTCLOUD_ADMIN_PASSWORD=admin_password #password for nextcloud admin's account 
      - MYSQL_HOST=nextcloud-mariadb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=topsecret
      - MYSQL_DATABASE=nextcloud_db
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=redis_password
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.server.com next.otner.server.org 192.168.11.2:8080
      - NEXTCLOUD_UPDATE=1
      - SMTP_HOST=smtp-relay.sendinblue.com #user SMTP server address
      - SMTP_SECURE=STARTTLS
      - SMTP_PORT=587
      - SMTP_AUTHTYPE=LOGIN
      - SMTP_NAME=login-for-smtp-server
      - SMTP_PASSWORD=smtp-server-password
      - MAIL_FROM_ADDRESS=yourmail@server.com
    volumes:
      - /home/user/dockerapps/nextcloud/config:/var/www/html
      - /mnt/4TB/move/Nextcloud/data:/var/www/html/data
    networks:
      - proxynet
    ports:
      - 8680:80
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: nextcloud-mariadb
    hostname: nextcloud-mariadb
    volumes:
      - /home/user/dockerapps/nextcloud/mariadb:/var/lib/mysql
    networks:
      - proxynet
    environment:
      - MARIADB_USER=username #set username for db
      - MARIADB_PASSWORD=secret #set user passeord for db
      - MARIADB_ROOT_PASSWORD=topsecret #set root password for db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    command: --requirepass redis_password
    volumes:
      - /home/user/dockerapps/nextcloud/redis:/data
    networks:
      - proxynet
    restart: unless-stopped

networks:
  proxynet:
    name: MyBridge
